### ISSUE TITLE
Do you plan to maintain this library for long time

### ISSUE THREAD

**Issue by elmcapp** [chipjarred/MacMenuBar#5]
I am planning to use this in my next project as I am not sure how to create NSMenu. I like to know do you plan to maintain this package or is it more of an example of what can be done

**Comment by chipjarred** [comment]
I’m glad to know you’re interested in using MacMenuBar. It isn’t just a demo of what can be done. I do plan to maintain it, because I want to continue using it for my own projects.  It needs some updating for SwiftUI projects that use WindowGroup instead of the older AppDelegate. I just haven’t been able to devote the time for it, though it shouldn’t be hard to adapt it - mainly just need to put the old delegate MacMenuBar startup code in an initializer for the WindowGroup, or whatever you make @main.  I also need to make a new Xcode project template for it and update the README accordingly.
